# Generated by Django 4.0 on 2021-12-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='size_ml',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_oz',
            field=models.IntegerField(),
        ),
    ]
